// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry          = require("bs-platform/lib/js/curry.js");
var Caml_oo_curry  = require("bs-platform/lib/js/caml_oo_curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var $$class = CamlinternalOO.create_table([
      "position",
      "tick",
      "follow"
    ]);

var ids = CamlinternalOO.new_methods_variables($$class, [
      "track",
      "tick",
      "position",
      "follow",
      "focus"
    ], [
      "focused",
      "position"
    ]);

var track = ids[0];

var tick = ids[1];

var position = ids[2];

var follow = ids[3];

var focus = ids[4];

var focused = ids[5];

var position$1 = ids[6];

CamlinternalOO.set_methods($$class, /* array */[
      follow,
      (function (self$1, character) {
          return Curry._2(self$1[0][focus], self$1, /* Subject */[character]);
        }),
      tick,
      (function (self$1, _) {
          var f = self$1[focused][0];
          if (f) {
            return Curry._2(self$1[0][track], self$1, f[0]);
          } else {
            return /* () */0;
          }
        }),
      position,
      (function (self$1, _) {
          return self$1[position$1][0];
        }),
      focus,
      (function (self$1, sub) {
          self$1[focused][0] = sub;
          return /* () */0;
        }),
      track,
      (function (self$1, c) {
          var d = Caml_oo_curry.js2(-1033677270, 1, c, /* () */0);
          self$1[position$1][0] = /* tuple */[
            d[/* x */0],
            d[/* y */1]
          ];
          return /* () */0;
        })
    ]);

function obj_init() {
  var self = CamlinternalOO.create_object_opt(0, $$class);
  self[focused] = [/* None */0];
  self[position$1] = [/* tuple */[
      0.0,
      0.0
    ]];
  return self;
}

CamlinternalOO.init_class($$class);

var camera = obj_init(0);

exports.camera = camera;
/* class Not a pure module */
