// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Renderable$Sweenyville = require("./renderable.bs.js");

var Character = Renderable$Sweenyville.MakeGameObject([
      Renderable$Sweenyville.next_coordinates,
      Renderable$Sweenyville.accel,
      Renderable$Sweenyville.decel
    ]);

var character = Character[/* spawn */0];

exports.Character = Character;
exports.character = character;
/* Character Not a pure module */
