// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives    = require("bs-platform/lib/js/pervasives.js");
var Caml_oo_curry = require("bs-platform/lib/js/caml_oo_curry.js");

function next_coordinates(scene, position, speed) {
  var newX = Pervasives.max(Caml_oo_curry.js2(761282246, 2, scene, /* () */0), Pervasives.min(Caml_oo_curry.js2(-405516197, 1, scene, /* () */0), position[0] + speed[0]));
  var newY = Pervasives.max(Caml_oo_curry.js2(-963970092, 4, scene, /* () */0), Pervasives.min(Caml_oo_curry.js2(-146710358, 3, scene, /* () */0), position[1] + speed[1]));
  return /* tuple */[
          newX,
          newY
        ];
}

function accel(direction, speed, maxSpeed) {
  var vy = speed[1];
  var vx = speed[0];
  switch (direction) {
    case 0 : 
        return /* tuple */[
                vx,
                Pervasives.max(vy - 0.2, 0.0 - maxSpeed)
              ];
    case 1 : 
        return /* tuple */[
                vx,
                Pervasives.min(vy + 0.2, maxSpeed)
              ];
    case 2 : 
        return /* tuple */[
                Pervasives.max(vx - 0.2, 0.0 - maxSpeed),
                vy
              ];
    case 3 : 
        return /* tuple */[
                Pervasives.min(vx + 0.2, maxSpeed),
                vy
              ];
    
  }
}

function decel(direction, vx, vy) {
  switch (direction) {
    case 0 : 
        return /* tuple */[
                +(vy < 0.0),
                vx,
                Pervasives.min(vy + 0.2, 0.0)
              ];
    case 1 : 
        return /* tuple */[
                +(vy > 0.0),
                vx,
                Pervasives.max(vy - 0.2, 0.0)
              ];
    case 2 : 
        return /* tuple */[
                +(vx < 0.0),
                Pervasives.min(vx + 0.2, 0.0),
                vy
              ];
    case 3 : 
        return /* tuple */[
                +(vx > 0.0),
                Pervasives.max(vx - 0.2, 0.0),
                vy
              ];
    
  }
}

exports.next_coordinates = next_coordinates;
exports.accel            = accel;
exports.decel            = decel;
/* No side effect */
