// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry          = require("bs-platform/lib/js/curry.js");
var Pervasives     = require("bs-platform/lib/js/pervasives.js");
var Caml_oo_curry  = require("bs-platform/lib/js/caml_oo_curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var class_tables = [
  0,
  0,
  0
];

function MakeGameObject(ObjectType) {
  var spawn = function (start_x, start_y) {
    if (!class_tables[0]) {
      var $$class = CamlinternalOO.create_table([
            "data",
            "tick",
            "decel",
            "accel"
          ]);
      var env = CamlinternalOO.new_variable($$class, "");
      var ids = CamlinternalOO.new_methods_variables($$class, [
            "tick",
            "setSpeedIf",
            "decel",
            "data",
            "accel"
          ], [
            "data",
            "maxSpeed"
          ]);
      var tick = ids[0];
      var setSpeedIf = ids[1];
      var decel = ids[2];
      var data = ids[3];
      var accel = ids[4];
      var data$1 = ids[5];
      var maxSpeed = ids[6];
      CamlinternalOO.set_methods($$class, /* array */[
            tick,
            (function (self$1, scene) {
                var match = Curry._3(self$1[env][0][/* next_coordinates */0], scene, /* tuple */[
                      self$1[data$1][/* x */0],
                      self$1[data$1][/* y */1]
                    ], /* tuple */[
                      self$1[data$1][/* vx */2],
                      self$1[data$1][/* vy */3]
                    ]);
                self$1[data$1][/* x */0] = match[0];
                self$1[data$1][/* y */1] = match[1];
                return /* () */0;
              }),
            accel,
            (function (self$1, direction) {
                var match = Curry._3(self$1[env][0][/* accel */1], direction, /* tuple */[
                      self$1[data$1][/* vx */2],
                      self$1[data$1][/* vy */3]
                    ], self$1[maxSpeed]);
                return Curry._4(self$1[0][setSpeedIf], self$1, /* true */1, match[0], match[1]);
              }),
            decel,
            (function (self$1, direction) {
                var match = Curry._3(self$1[env][0][/* decel */2], direction, self$1[data$1][/* vx */2], self$1[data$1][/* vy */3]);
                return Curry._4(self$1[0][setSpeedIf], self$1, match[0], match[1], match[2]);
              }),
            data,
            (function (self$1, _) {
                return self$1[data$1];
              }),
            setSpeedIf,
            (function (self$1, going, vx, vy) {
                if (going) {
                  self$1[data$1][/* vx */2] = vx;
                  self$1[data$1][/* vy */3] = vy;
                  return /* () */0;
                } else {
                  return 0;
                }
              })
          ]);
      var env_init = function (env$1) {
        var self = CamlinternalOO.create_object_opt(0, $$class);
        self[data$1] = /* float array */[
          env$1[1],
          env$1[2],
          0.0,
          0.0
        ];
        self[maxSpeed] = 8.0;
        self[env] = env$1[0];
        return self;
      };
      CamlinternalOO.init_class($$class);
      class_tables[0] = env_init;
    }
    return Curry._1(class_tables[0], [
                [ObjectType],
                start_x,
                start_y
              ]);
  };
  return /* module */[/* spawn */spawn];
}

function next_coordinates(scene, position, speed) {
  var newX = Pervasives.max(Caml_oo_curry.js2(761282246, 2, scene, /* () */0), Pervasives.min(Caml_oo_curry.js2(-405516197, 1, scene, /* () */0), position[0] + speed[0]));
  var newY = Pervasives.max(Caml_oo_curry.js2(-963970092, 4, scene, /* () */0), Pervasives.min(Caml_oo_curry.js2(-146710358, 3, scene, /* () */0), position[1] + speed[1]));
  return /* tuple */[
          newX,
          newY
        ];
}

function accel(direction, speed, maxSpeed) {
  var vy = speed[1];
  var vx = speed[0];
  switch (direction) {
    case 0 : 
        return /* tuple */[
                vx,
                Pervasives.max(vy - 0.2, 0.0 - maxSpeed)
              ];
    case 1 : 
        return /* tuple */[
                vx,
                Pervasives.min(vy + 0.2, maxSpeed)
              ];
    case 2 : 
        return /* tuple */[
                Pervasives.max(vx - 0.2, 0.0 - maxSpeed),
                vy
              ];
    case 3 : 
        return /* tuple */[
                Pervasives.min(vx + 0.2, maxSpeed),
                vy
              ];
    
  }
}

function decel(direction, vx, vy) {
  switch (direction) {
    case 0 : 
        return /* tuple */[
                +(vy < 0.0),
                vx,
                Pervasives.min(vy + 0.2, 0.0)
              ];
    case 1 : 
        return /* tuple */[
                +(vy > 0.0),
                vx,
                Pervasives.max(vy - 0.2, 0.0)
              ];
    case 2 : 
        return /* tuple */[
                +(vx < 0.0),
                Pervasives.min(vx + 0.2, 0.0),
                vy
              ];
    case 3 : 
        return /* tuple */[
                +(vx > 0.0),
                Pervasives.max(vx - 0.2, 0.0),
                vy
              ];
    
  }
}

exports.MakeGameObject   = MakeGameObject;
exports.next_coordinates = next_coordinates;
exports.accel            = accel;
exports.decel            = decel;
/* No side effect */
