// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Renderable$Sweenyville = require("./renderable.bs.js");

var category = /* Tile */[/* false */0];

function next_coordinates(_, param, _$1) {
  return /* tuple */[
          param[0],
          param[1]
        ];
}

var TileObject = /* module */[
  /* MakeGameObject */Renderable$Sweenyville.MakeGameObject,
  /* accel */Renderable$Sweenyville.accel,
  /* decel */Renderable$Sweenyville.decel,
  /* check_collisions */Renderable$Sweenyville.check_collisions,
  /* category */category,
  /* next_coordinates */next_coordinates
];

var Tile = Renderable$Sweenyville.MakeGameObject([
      category,
      next_coordinates,
      Renderable$Sweenyville.accel,
      Renderable$Sweenyville.decel,
      Renderable$Sweenyville.check_collisions
    ]);

var spawn = Tile[/* spawn */0];

exports.TileObject = TileObject;
exports.Tile       = Tile;
exports.spawn      = spawn;
/* Tile Not a pure module */
