// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array              = require("bs-platform/lib/js/array.js");
var Hero$Sweenyville     = require("./hero.bs.js");
var Predator$Sweenyville = require("./predator.bs.js");

var textures = $$Array.concat(/* :: */[
      /* array */[
        "images/space.jpg",
        "images/tiles.jpeg"
      ],
      /* :: */[
        Predator$Sweenyville.frame_sequence("idle", 3),
        /* :: */[
          Predator$Sweenyville.frame_sequence("run", 6),
          /* :: */[
            Hero$Sweenyville.frame_sequence("Idle", 16),
            /* :: */[
              Hero$Sweenyville.frame_sequence("Run", 20),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

exports.textures = textures;
/* textures Not a pure module */
