// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array                = require("bs-platform/lib/js/array.js");
var Caml_int32             = require("bs-platform/lib/js/caml_int32.js");
var Caml_oo_curry          = require("bs-platform/lib/js/caml_oo_curry.js");
var Dom$Sweenyville        = require("./dom.bs.js");
var Pixi$Sweenyville       = require("./pixi.bs.js");
var Scene$Sweenyville      = require("../game/scene.bs.js");
var Camera$Sweenyville     = require("../game/camera.bs.js");
var Predator$Sweenyville   = require("./predator.bs.js");
var Controller$Sweenyville = require("../game/controller.bs.js");

function boot(app, hero, enemies, tiles, background) {
  var animator = hero[2];
  var my_hero = hero[1];
  var player = hero[0];
  Pixi$Sweenyville.Sprite[/* interact */5](my_hero);
  Pixi$Sweenyville.Sprite[/* button */6](my_hero);
  Pixi$Sweenyville.Sprite[/* listen */7](my_hero, "mouseover", (function () {
          return Pixi$Sweenyville.Sprite[/* alpha */9](my_hero, 0.8);
        }));
  Pixi$Sweenyville.Sprite[/* listen */7](my_hero, "mouseout", (function () {
          return Pixi$Sweenyville.Sprite[/* alpha */9](my_hero, 1.0);
        }));
  Pixi$Sweenyville.Sprite[/* listen */7](my_hero, "click", (function () {
          return Caml_oo_curry.js2(432628799, 1, animator, Predator$Sweenyville.sequence_map);
        }));
  var r = Pixi$Sweenyville.App[/* renderer */12](app);
  var bg = Pixi$Sweenyville.App[/* tiling_sprite */7](Pixi$Sweenyville.App[/* texture */4](background), Pixi$Sweenyville.App[/* width */13](r), Pixi$Sweenyville.App[/* height */14](r));
  var match_000 = Caml_int32.imul(Pixi$Sweenyville.App[/* width */13](r), 3);
  var match_001 = Caml_int32.imul(Pixi$Sweenyville.App[/* height */14](r), 3);
  var objects = $$Array.concat(/* :: */[
        $$Array.map((function (param) {
                return param[0];
              }), tiles),
        /* :: */[
          $$Array.map((function (param) {
                  return param[0];
                }), enemies),
          /* [] */0
        ]
      ]);
  var sprites = $$Array.concat(/* :: */[
        $$Array.map((function (param) {
                return param[1];
              }), tiles),
        /* :: */[
          $$Array.map((function (param) {
                  return param[1];
                }), enemies),
          /* [] */0
        ]
      ]);
  var scene = Scene$Sweenyville.scene(match_000, match_001, $$Array.append(/* array */[player], objects));
  Pixi$Sweenyville.App[/* addSprites */16](app, $$Array.append(/* array */[
            bg,
            my_hero
          ], sprites));
  var controller = Controller$Sweenyville.controller(player);
  Dom$Sweenyville.listen("keydown", (function ($$event) {
          var d = Dom$Sweenyville.key_map($$event);
          Caml_oo_curry.js2(-933174511, 2, controller, d);
          if (d) {
            return Caml_oo_curry.js2(-855250051, 3, player, d[0]);
          } else {
            return /* () */0;
          }
        }));
  Dom$Sweenyville.listen("keyup", (function ($$event) {
          var d = Dom$Sweenyville.key_map($$event);
          return Caml_oo_curry.js2(-866390014, 4, controller, d);
        }));
  Caml_oo_curry.js2(-107572879, 5, Camera$Sweenyville.camera, player);
  var match_000$1 = Pixi$Sweenyville.App[/* width */13](r) / 2 | 0;
  var match_001$1 = Pixi$Sweenyville.App[/* height */14](r) / 2 | 0;
  var app_center_y = match_001$1;
  var app_center_x = match_000$1;
  return Pixi$Sweenyville.App[/* add_ticker */11](app, (function () {
                var data = Caml_oo_curry.js2(-1033677270, 6, player, /* () */0);
                var gap_left = data[/* x */0] - Caml_oo_curry.js2(761282246, 7, scene, /* () */0);
                var gap_right = Caml_oo_curry.js2(-405516197, 8, scene, /* () */0) - data[/* x */0];
                var gap_top = Math.abs(Caml_oo_curry.js2(-963970092, 9, scene, /* () */0) - data[/* y */1]);
                var gap_bottom = Math.abs(data[/* y */1] - Caml_oo_curry.js2(-146710358, 10, scene, /* () */0));
                var margin = function (gap, dimension) {
                  return +((gap | 0) < (dimension / 2 | 0));
                };
                var side_margin = function (gap) {
                  return margin(gap, Pixi$Sweenyville.App[/* width */13](r));
                };
                var v_margin = function (gap) {
                  return margin(gap, Pixi$Sweenyville.App[/* height */14](r));
                };
                if (side_margin(gap_left) || side_margin(gap_right)) {
                  Caml_oo_curry.js2(-443041036, 11, Camera$Sweenyville.camera, /* () */0);
                } else {
                  Caml_oo_curry.js2(-510017093, 12, Camera$Sweenyville.camera, /* () */0);
                }
                if (v_margin(gap_top) || v_margin(gap_bottom)) {
                  Caml_oo_curry.js2(-443041035, 13, Camera$Sweenyville.camera, /* () */0);
                } else {
                  Caml_oo_curry.js2(-510017092, 14, Camera$Sweenyville.camera, /* () */0);
                }
                Caml_oo_curry.js2(-855850147, 15, controller, /* () */0);
                Caml_oo_curry.js2(-855850147, 16, scene, /* () */0);
                Caml_oo_curry.js2(-855850147, 17, Camera$Sweenyville.camera, /* () */0);
                Caml_oo_curry.js2(-855850147, 18, animator, /* () */0);
                $$Array.iter((function (param) {
                        var tmp = param[2];
                        return Caml_oo_curry.js2(-855850147, 19, tmp, /* () */0);
                      }), enemies);
                var match = Caml_oo_curry.js2(-889544535, 20, Camera$Sweenyville.camera, /* () */0);
                var camera_y = match[1];
                var camera_x = match[0];
                var put = function (param) {
                  var sprite = param[1];
                  var renderable = param[0];
                  var data = Caml_oo_curry.js2(-1033677270, 21, renderable, /* () */0);
                  var match_000 = app_center_x + (data[/* x */0] - camera_x);
                  var match_001 = app_center_y + (data[/* y */1] - camera_y);
                  var match = Pixi$Sweenyville.Sprite[/* center_offset */10](sprite);
                  Pixi$Sweenyville.Sprite[/* position */4](sprite, match_000 - match[0], match_001 - match[1]);
                  var d = Caml_oo_curry.js2(272654911, 22, renderable, /* () */0);
                  if (d >= 2) {
                    switch (d - 2 | 0) {
                      case 0 : 
                          return Pixi$Sweenyville.Sprite[/* flip_left */2](sprite);
                      case 1 : 
                          return Pixi$Sweenyville.Sprite[/* flip_right */1](sprite);
                      case 2 : 
                          return /* () */0;
                      
                    }
                  } else {
                    return /* () */0;
                  }
                };
                $$Array.iter((function (param) {
                        var param$1 = /* tuple */[
                          param[0],
                          param[1]
                        ];
                        var sprite = param$1[1];
                        var tmp = param$1[0];
                        var data = Caml_oo_curry.js2(-1033677270, 23, tmp, /* () */0);
                        var match_000 = app_center_x + (data[/* x */0] - camera_x);
                        var match_001 = app_center_y + (data[/* y */1] - camera_y);
                        var match = Pixi$Sweenyville.Sprite[/* center_offset */10](my_hero);
                        var hero_center_x = match[0];
                        var match$1 = Pixi$Sweenyville.Sprite[/* center_offset */10](sprite);
                        return Pixi$Sweenyville.Sprite[/* position */4](sprite, match_000 - hero_center_x + match$1[0] - hero_center_x, match_001 - match[1]);
                      }), tiles);
                put(/* tuple */[
                      player,
                      my_hero
                    ]);
                return $$Array.iter((function (param) {
                              return put(/* tuple */[
                                          param[0],
                                          param[1]
                                        ]);
                            }), enemies);
              }));
}

exports.boot = boot;
/* Pixi-Sweenyville Not a pure module */
