// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives            = require("bs-platform/lib/js/pervasives.js");
var Animation$Sweenyville = require("./animation.bs.js");

function texture_name(sequence, frame) {
  return "images/hero/" + (sequence + (" (" + (Pervasives.string_of_int(frame) + ").png")));
}

function frame_sequence(param, param$1) {
  return Animation$Sweenyville.frame_sequence_generator(texture_name, param, param$1);
}

var generator = Animation$Sweenyville.sequence_info_generator(texture_name);

var sequence_map_000 = /* idle */generator(16, "Idle");

var sequence_map_001 = /* running */generator(20, "Run");

var sequence_map = /* record */[
  sequence_map_000,
  sequence_map_001
];

exports.texture_name   = texture_name;
exports.frame_sequence = frame_sequence;
exports.generator      = generator;
exports.sequence_map   = sequence_map;
/* generator Not a pure module */
