// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry                 = require("bs-platform/lib/js/curry.js");
var Pixi$Sweenyville      = require("./pixi.bs.js");
var Animation$Sweenyville = require("./animation.bs.js");
var Character$Sweenyville = require("../game/character.bs.js");

function spawn(coords, map) {
  var match = map[/* idle */0];
  var sprite = Pixi$Sweenyville.App[/* sprite */5](Curry._1(match[1], 1));
  var character = Curry._2(Character$Sweenyville.character, coords[0], coords[1]);
  var animator = Animation$Sweenyville.animator(character, sprite, map);
  return /* tuple */[
          character,
          sprite,
          animator
        ];
}

exports.spawn = spawn;
/* Pixi-Sweenyville Not a pure module */
