// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry            = require("bs-platform/lib/js/curry.js");
var Caml_oo_curry    = require("bs-platform/lib/js/caml_oo_curry.js");
var CamlinternalOO   = require("bs-platform/lib/js/camlinternalOO.js");
var Pixi$Sweenyville = require("./pixi.bs.js");

var class_tables = [
  0,
  0,
  0
];

function animator(player, sprite, map) {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table(["tick"]);
    var env = CamlinternalOO.new_variable($$class, "");
    var ids = CamlinternalOO.new_methods_variables($$class, [
          "updateTexture",
          "tick",
          "maxFrames",
          "current_info",
          "animate"
        ], [
          "ticks",
          "frame",
          "seq"
        ]);
    var updateTexture = ids[0];
    var tick = ids[1];
    var maxFrames = ids[2];
    var current_info = ids[3];
    var animate = ids[4];
    var ticks = ids[5];
    var frame = ids[6];
    var seq = ids[7];
    CamlinternalOO.set_methods($$class, /* array */[
          tick,
          (function (self$1, _) {
              self$1[ticks][0] = self$1[ticks][0] + 1 | 0;
              if (self$1[ticks][0] === 3) {
                Curry._2(self$1[0][animate], self$1, /* () */0);
                self$1[ticks][0] = 0;
                return /* () */0;
              } else {
                return 0;
              }
            }),
          animate,
          (function (self$1, _) {
              var tmp = self$1[env][2];
              var d = Caml_oo_curry.js2(-1033677270, 2, tmp, /* () */0);
              var moving = +(d[/* vx */2] !== 0.0 || d[/* vy */3] !== 0.0);
              var nextSeq = moving !== 0 ? /* Running */0 : /* Idle */1;
              if (nextSeq !== self$1[seq][0]) {
                self$1[frame][0] = 1;
                self$1[seq][0] = nextSeq;
              } else {
                var match = +(self$1[frame][0] === Curry._2(self$1[0][maxFrames], self$1, /* () */0));
                self$1[frame][0] = match !== 0 ? 1 : self$1[frame][0] + 1 | 0;
              }
              return Curry._2(self$1[0][updateTexture], self$1, /* () */0);
            }),
          current_info,
          (function (self$1, _) {
              var env$1 = self$1[env];
              var match = self$1[seq][0];
              if (match !== 0) {
                return env$1[1][/* idle */0];
              } else {
                return env$1[1][/* running */1];
              }
            }),
          maxFrames,
          (function (self$1, _) {
              return Curry._2(self$1[0][current_info], self$1, /* () */0)[0];
            }),
          updateTexture,
          (function (self$1, _) {
              var match = Curry._2(self$1[0][current_info], self$1, /* () */0);
              return Pixi$Sweenyville.Sprite[/* setTexture */2](self$1[env][0], Pixi$Sweenyville.App[/* texture */4](Curry._1(match[1], self$1[frame][0])));
            })
        ]);
    var env_init = function (env$1) {
      var self = CamlinternalOO.create_object_opt(0, $$class);
      self[ticks] = [0];
      self[frame] = [1];
      self[seq] = [/* Idle */1];
      self[env] = env$1;
      return self;
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], [
              sprite,
              map,
              player
            ]);
}

exports.animator = animator;
/* Pixi-Sweenyville Not a pure module */
