// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry          = require("bs-platform/lib/js/curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var shared = ["tick"];

var class_tables = [
  0,
  0,
  0
];

function animator(_, _$1) {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table(shared);
    var ids = CamlinternalOO.new_methods_variables($$class, shared, ["ticks"]);
    var tick = ids[0];
    var ticks = ids[1];
    CamlinternalOO.set_method($$class, tick, (function (self$1, _) {
            if (self$1[ticks][0] === 10) {
              self$1[ticks][0] = 0;
              return /* () */0;
            } else {
              return 0;
            }
          }));
    var env_init = function () {
      var self = CamlinternalOO.create_object_opt(0, $$class);
      self[ticks] = [0];
      return self;
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], 0);
}

exports.animator = animator;
/* No side effect */
