// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry          = require("bs-platform/lib/js/curry.js");
var Pervasives     = require("bs-platform/lib/js/pervasives.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var class_tables = [
  0,
  0,
  0
];

function character(startX, startY) {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table([
          "data",
          "place",
          "tick",
          "advance",
          "degrade"
        ]);
    var ids = CamlinternalOO.new_methods_variables($$class, [
          "turn",
          "tick",
          "setSpeedIf",
          "place",
          "degrade",
          "data",
          "advance"
        ], [
          "maxSpeed",
          "position",
          "speed",
          "d"
        ]);
    var turn = ids[0];
    var tick = ids[1];
    var setSpeedIf = ids[2];
    var place = ids[3];
    var degrade = ids[4];
    var data = ids[5];
    var advance = ids[6];
    var maxSpeed = ids[7];
    var position = ids[8];
    var speed = ids[9];
    var d = ids[10];
    CamlinternalOO.set_methods($$class, /* array */[
          tick,
          (function (self$1, _) {
              var match = self$1[position][0];
              var match$1 = self$1[speed][0];
              self$1[position][0] = /* tuple */[
                match[0] + match$1[0] | 0,
                match[1] + match$1[1] | 0
              ];
              return /* () */0;
            }),
          place,
          (function (self$1, newX, newY) {
              self$1[position][0] = /* tuple */[
                newX,
                newY
              ];
              return /* () */0;
            }),
          advance,
          (function (self$1, direction) {
              var match = self$1[speed][0];
              var vy = match[1];
              var vx = match[0];
              switch (direction) {
                case 0 : 
                    self$1[speed][0] = /* tuple */[
                      vx,
                      Pervasives.max(vy - 1 | 0, -self$1[maxSpeed][0] | 0)
                    ];
                    return /* () */0;
                case 1 : 
                    self$1[speed][0] = /* tuple */[
                      vx,
                      Pervasives.min(vy + 1 | 0, self$1[maxSpeed][0])
                    ];
                    return /* () */0;
                case 2 : 
                    self$1[speed][0] = /* tuple */[
                      Pervasives.max(vx - 1 | 0, -self$1[maxSpeed][0] | 0),
                      vy
                    ];
                    return /* () */0;
                case 3 : 
                    self$1[speed][0] = /* tuple */[
                      Pervasives.min(vx + 1 | 0, self$1[maxSpeed][0]),
                      vy
                    ];
                    return /* () */0;
                
              }
            }),
          degrade,
          (function (self$1, direction) {
              var match = self$1[speed][0];
              var vy = match[1];
              var vx = match[0];
              switch (direction) {
                case 0 : 
                    return Curry._4(self$1[0][setSpeedIf], self$1, +(vy < 0), vx, Pervasives.min(vy + 1 | 0, 0));
                case 1 : 
                    return Curry._4(self$1[0][setSpeedIf], self$1, +(vy > 0), vx, Pervasives.max(vy - 1 | 0, 0));
                case 2 : 
                    return Curry._4(self$1[0][setSpeedIf], self$1, +(vx < 0), Pervasives.min(vx + 1 | 0, 0), vy);
                case 3 : 
                    return Curry._4(self$1[0][setSpeedIf], self$1, +(vx > 0), Pervasives.max(vx - 1 | 0, 0), vy);
                
              }
            }),
          data,
          (function (self$1, _) {
              var match = self$1[position][0];
              var match$1 = self$1[speed][0];
              return /* record */[
                      /* x */match[0],
                      /* y */match[1],
                      /* vx */match$1[0],
                      /* vy */match$1[1],
                      /* direction */self$1[d][0]
                    ];
            }),
          setSpeedIf,
          (function (self$1, going, vx, vy) {
              if (going) {
                self$1[speed][0] = /* tuple */[
                  vx,
                  vy
                ];
                return /* () */0;
              } else {
                return 0;
              }
            }),
          turn,
          (function (self$1, direction) {
              self$1[d][0] = direction;
              return /* () */0;
            })
        ]);
    var env_init = function (env) {
      var self = CamlinternalOO.create_object_opt(0, $$class);
      self[maxSpeed] = [15];
      self[position] = [/* tuple */[
          env[1],
          env[2]
        ]];
      self[speed] = [/* tuple */[
          0,
          0
        ]];
      self[d] = [/* Right */3];
      return self;
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], [
              0,
              startX,
              startY
            ]);
}

exports.character = character;
/* No side effect */
