// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function $$window$1() {
  return window;
}

function listen(name, h) {
  window.addEventListener(name, h);
  return /* () */0;
}

function keycode($$event) {
  return $$event.keyCode;
}

function keyMap(e) {
  var code = e.keyCode;
  var switcher = code - 37 | 0;
  if (switcher > 3 || switcher < 0) {
    return /* None */4;
  } else {
    switch (switcher) {
      case 0 : 
          return /* Left */2;
      case 1 : 
          return /* Up */0;
      case 2 : 
          return /* Right */3;
      case 3 : 
          return /* Down */1;
      
    }
  }
}

exports.$$window = $$window$1;
exports.listen   = listen;
exports.keycode  = keycode;
exports.keyMap   = keyMap;
/* No side effect */
