// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array                = require("bs-platform/lib/js/array.js");
var Pervasives             = require("bs-platform/lib/js/pervasives.js");
var Caml_oo_curry          = require("bs-platform/lib/js/caml_oo_curry.js");
var Dom$Sweenyville        = require("./dom.bs.js");
var Pixi$Sweenyville       = require("./pixi.bs.js");
var Animation$Sweenyville  = require("./animation.bs.js");
var Character$Sweenyville  = require("./character.bs.js");
var Controller$Sweenyville = require("./controller.bs.js");
var Reasonable$Sweenyville = require("./reasonable.bs.js");

function start() {
  var app = Pixi$Sweenyville.App[/* start */0](/* () */0);
  var textureName = function (sequence, frame) {
    return "images/hero/" + (sequence + (" (" + (Pervasives.string_of_int(frame) + ").png")));
  };
  var frameSequence = function (name, numFrames) {
    return $$Array.map((function (n) {
                  return textureName(name, n);
                }), Reasonable$Sweenyville.range(1, numFrames));
  };
  var textures = $$Array.append(frameSequence("Idle", 16), frameSequence("Run", 20));
  var callback = function (_, resources) {
    var myHero = Pixi$Sweenyville.App[/* fetchSprite */6](resources, "images/hero/Idle (1).png");
    Pixi$Sweenyville.Sprite[/* rescale */0](myHero, 0.2, 0.2);
    var r = Pixi$Sweenyville.App[/* renderer */8](app);
    var player = Character$Sweenyville.character(Pixi$Sweenyville.App[/* width */9](r) / 2 | 0, Pixi$Sweenyville.App[/* height */10](r) / 2 | 0);
    var map_000 = /* idle : SequenceInfo */[
      16,
      (function (param) {
          return textureName("Idle", param);
        })
    ];
    var map_001 = /* running : SequenceInfo */[
      20,
      (function (param) {
          return textureName("Run", param);
        })
    ];
    var map = /* record */[
      map_000,
      map_001
    ];
    var animator = Animation$Sweenyville.animator(player, myHero, map);
    Pixi$Sweenyville.Sprite[/* position */1](myHero, Caml_oo_curry.js2(-1033677270, 2, player, /* () */0)[/* x */0], Caml_oo_curry.js2(-1033677270, 1, player, /* () */0)[/* y */1]);
    Pixi$Sweenyville.App[/* addSprite */11](app, myHero);
    var controller = Controller$Sweenyville.controller(player);
    Dom$Sweenyville.listen("keydown", (function ($$event) {
            var d = Dom$Sweenyville.keyMap($$event);
            Caml_oo_curry.js2(-933174511, 3, controller, d);
            if (d) {
              var match = d[0];
              if (match !== 2) {
                if (match >= 3) {
                  return Pixi$Sweenyville.Sprite[/* rescale */0](myHero, 0.2, 0.2);
                } else {
                  return /* () */0;
                }
              } else {
                return Pixi$Sweenyville.Sprite[/* rescale */0](myHero, -0.2, 0.2);
              }
            } else {
              return /* () */0;
            }
          }));
    Dom$Sweenyville.listen("keyup", (function ($$event) {
            var d = Dom$Sweenyville.keyMap($$event);
            return Caml_oo_curry.js2(-866390014, 4, controller, d);
          }));
    return Pixi$Sweenyville.App[/* addTicker */7](app, (function () {
                  Caml_oo_curry.js2(-855850147, 5, controller, /* () */0);
                  var data = Caml_oo_curry.js2(-1033677270, 6, player, /* () */0);
                  Pixi$Sweenyville.Sprite[/* position */1](myHero, data[/* x */0], data[/* y */1]);
                  return Caml_oo_curry.js2(-855850147, 7, animator, /* () */0);
                }));
  };
  Pixi$Sweenyville.App[/* loadTextures */5](textures, callback);
  return app;
}

exports.start = start;
/* Pixi-Sweenyville Not a pure module */
