// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var PixiJs = require("pixi.js");

function spriteToJs(param) {
  return {
          x: param[/* x */0],
          y: param[/* y */1],
          vx: param[/* vx */2],
          vy: param[/* vy */3],
          scale: param[/* scale */4]
        };
}

function spriteFromJs(param) {
  return /* record */[
          /* x */param.x,
          /* y */param.y,
          /* vx */param.vx,
          /* vy */param.vy,
          /* scale */param.scale
        ];
}

function start() {
  console.log("hello");
  var app = new PixiJs.Application();
  var callback = function (_, resources) {
    debugger;
    var t = resources.hero.texture;
    var myHero = new PixiJs.Sprite(t);
    app.stage.addChild(myHero);
    return /* () */0;
  };
  var withTexture = PixiJs.loader.add("hero", "images/hero/Idle (1).png");
  withTexture.load(callback);
  return app;
}

exports.spriteToJs   = spriteToJs;
exports.spriteFromJs = spriteFromJs;
exports.start        = start;
/* pixi.js Not a pure module */
