// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var PixiJs = require("pixi.js");

function rescale(sprite, x, y) {
  var s = sprite.scale;
  s.x = x;
  s.y = y;
  return /* () */0;
}

function position(sprite, x, y) {
  sprite.anchor.x = 0.5;
  sprite.x = x;
  sprite.y = y;
  return /* () */0;
}

var Sprite = /* module */[
  /* rescale */rescale,
  /* position */position
];

function start() {
  return new PixiJs.Application();
}

function addTexture(prim, prim$1) {
  return prim.add(prim$1);
}

function getTexture(prim) {
  return prim.texture;
}

function loadTexture(path, callback) {
  PixiJs.loader.add(path).load(callback);
  return /* () */0;
}

function fetchSprite(resources, path) {
  return new PixiJs.Sprite(resources[path].texture);
}

function addTicker(app, tick) {
  app.ticker.add(tick);
  return /* () */0;
}

function renderer(prim) {
  return prim.renderer;
}

function width(prim) {
  return prim.width;
}

function height(prim) {
  return prim.height;
}

function addSprite(app, sprite) {
  app.stage.addChild(sprite);
  return /* () */0;
}

var App = /* module */[
  /* start */start,
  /* addTexture */addTexture,
  /* getTexture */getTexture,
  /* loadTexture */loadTexture,
  /* fetchSprite */fetchSprite,
  /* addTicker */addTicker,
  /* renderer */renderer,
  /* width */width,
  /* height */height,
  /* addSprite */addSprite
];

exports.Sprite = Sprite;
exports.App    = App;
/* pixi.js Not a pure module */
